SEO-3147 Angular Desc too long short
syncfusion-content/angular-docs pull request #225
Opened 2023-01-27 11:52 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan ,

Please review the changes for Angular Desc too long short.

Regards,
Yvone.

2023-01-27 11:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2217/console)**

2023-01-27 11:54 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2217/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-01-27 11:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2218/console)**

2023-01-27 11:55 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2218/artifact/cireports/)<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2218/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2218/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2218/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2218/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2218/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2218/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2218/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-01 08:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2222/console)**

2023-02-01 08:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2222/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2222/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2222/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2222/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2222/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2222/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2222/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-07 12:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2226/console)**

2023-02-07 12:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2226/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2226/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2226/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2226/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2226/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2226/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2226/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-08 12:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2227/console)**

2023-02-08 12:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2227/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2227/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2227/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2227/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2227/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2227/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2227/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-08 12:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2228/console)**

2023-02-08 12:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2228/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2228/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2228/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2228/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2228/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2228/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2228/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-09 12:04 UTC, Aishwarya-Ganesan commented on angular/DateTimePicker/Getting-Started.md
> +# Getting Started with Essential Angular DateTimePicker
Remove Essential word.

2023-02-09 12:05 UTC, Aishwarya-Ganesan reviewed
Commented.

2023-02-09 12:07 UTC, Yvone-Atieno commented on angular/DateTimePicker/Getting-Started.md
> +# Getting Started with Essential Angular DateTimePicker
removed

2023-02-09 12:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2230/console)**

2023-02-09 12:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2230/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2230/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2230/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2230/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2230/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2230/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2230/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-17 06:30 UTC, gowthamanthavasiyappan requested changes

2023-02-17 06:30 UTC, gowthamanthavasiyappan commented on angular/ReportViewer/Getting-Started.md
> +# Getting Started with Essential Angular ReportViewer
Remove `Essential` word.

2023-02-17 06:30 UTC, gowthamanthavasiyappan commented on angular/Grid/Overview.md
> +# Overview in Essential Angular Grid
Remove Essential word.

2023-02-17 06:30 UTC, gowthamanthavasiyappan commented
Commented

2023-02-17 06:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2235/console)**

2023-02-17 06:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-Angular-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2235/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2235/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2235/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2235/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2235/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2235/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2235/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-17 06:46 UTC, Yvone-Atieno commented on angular/Grid/Overview.md
> +# Overview in Essential Angular Grid
changed

2023-02-17 06:46 UTC, Yvone-Atieno commented on angular/ReportViewer/Getting-Started.md
> +# Getting Started with Essential Angular ReportViewer
changed

2023-02-17 07:09 UTC, gowthamanthavasiyappan approved these changes

2023-02-21 05:40 UTC, Aishwarya-Ganesan reviewed
Changes are fine.

2023-02-21 05:40 UTC, merged