SEO-176496-Angular-page-with-redirect-links
syncfusion-content/angular-docs pull request #320
Opened 2023-10-15 08:40 UTC by Edithabich

HI @MallikaRK ,
Please review the changes.

Thanks.

Regards,
Edith.

2023-10-15 08:41 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176496-Angular-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2299/console)**

2023-10-15 08:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176496-Angular-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2299/console)**

2023-10-15 08:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176496-Angular-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2299/)<br/>**

2023-10-17 08:23 UTC, Yvone-Atieno requested changes
Commented

2023-10-17 12:53 UTC, Edithabich commented on angular/Gantt/Data-Binding.md
> +            url: "https://js.syncfusion.com/demos/ejServices/Wcf/TreeGridGantt/TreeGantt.svc/SelfReferenceDatas",
resolved

2023-10-17 12:53 UTC, Edithabich commented on angular/Gantt/Data-Binding.md
> +            url: "https://js.syncfusion.com/demos/ejServices/Wcf/TreeGridGantt/TreeGantt.svc/SelfReferenceDatas"
resolved

2023-10-17 12:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176496-Angular-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2301/)<br/>**

2023-11-10 15:10 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176496-Angular-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2307/console)**

2023-11-10 15:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176496-Angular-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2307/console)**

2023-11-10 15:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176496-Angular-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/angular-docs/2307/)<br/>**

2023-11-16 06:25 UTC, Yvone-Atieno approved these changes
Approved

2024-01-04 14:10 UTC, merged