SEO-187452-Angular-Title-too-long/short
syncfusion-content/angular-docs pull request #376
Opened 2024-08-28 12:22 UTC by Edithabich

Hi @Yvone-Atieno,

|Title|Description|
|--|--|
|Category|Title too long/short link |
|Hotfix PR|https://github.com/syncfusion-content/angular-docs/pull/376|
|Task||
|Content Ticket||
|UX Ticket||

|Changes made|Reason for changes|
|--|--|
|Modify meta elements|For meta alignment with proper character count|
|Removed # tag|To have h1 in the page for proper alignment|

Regards,
Edith.

2024-08-28 12:27 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/angular-docs/22/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-08-28 12:27 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/23/console)**

2024-08-28 13:06 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/angular-docs/22/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-08-28 13:07 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/23/)<br/>**

2024-08-28 13:07 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: FAILURE :x:<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/22/)<br/>**

2024-08-28 13:07 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/25/console)**

2024-08-28 13:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/24/console)**

2024-08-28 14:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/25/console)**

2024-08-28 14:15 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/angular-docs/25/artifact/cireports/)<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/25/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/25/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/25/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/25/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/25/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/angular-docs/25/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/25/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/25/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/25/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-29 13:26 UTC, Yvone-Atieno requested changes
Commented

2024-08-29 13:26 UTC, Yvone-Atieno commented on angular/Listview/Overview.md
> +title: Overview of Angular Listview | Syncfusion
Use ListView in all places

2024-08-29 13:33 UTC, Edithabich commented on angular/Listview/Overview.md
> +title: Overview of Angular Listview | Syncfusion
resolved

2024-08-29 13:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/27/console)**

2024-08-29 13:40 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/angular-docs/27/artifact/cireports/)<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/27/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/27/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/27/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/27/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/27/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/angular-docs/27/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/27/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/27/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/27/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-29 14:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/28/console)**

2024-08-29 14:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/28/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/28/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/28/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/28/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/28/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/28/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/28/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/28/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/28/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-29 14:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/29/console)**

2024-08-29 14:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187452-Angular-Title-too-long/short](https://ci.syncfusion.com/job/Content/job/angular-docs/29/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/29/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/29/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/29/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/29/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/29/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/29/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/29/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/angular-docs/29/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-05 06:37 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-09-05 06:38 UTC, Yvone-Atieno approved these changes
Approved

2024-09-05 06:39 UTC, merged